name: safeeats1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

  # Firebase packages (latest compatible versions)
  firebase_core: ^3.10.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2
  mobile_scanner: ^3.0.0

  # Other dependencies
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
