class IngredientInfo {
  final String name;
  final bool banned;
  final bool affectsDiabetes;
  final bool affectsCholesterol;
  final bool affectsFattyLiver;
  final bool affectsWeightGain;
  final bool affectsWeightLoss;

  IngredientInfo({
    required this.name,
    this.banned = false,
    this.affectsDiabetes = false,
    this.affectsCholesterol = false,
    this.affectsFattyLiver = false,
    this.affectsWeightGain = false,
    this.affectsWeightLoss = false,
  });
}

final List<IngredientInfo> ingredientsDatabase = [
  // --- Regular Ingredients ---
  // --- Cholesterol / Fat-related ingredients ---
  IngredientInfo(name: "Palm kernel oil", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Coconut oil", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Hydrogenated vegetable oil", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Margarine", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Butter oil", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Cream powder", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Cheese powder", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Animal fat", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Palm oil", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Palm olein", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Palm stearin", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Vegetable fat", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Cocoa butter", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Lard", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Shortening", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Hydrogenated oil", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Margarine powder", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Ghee", affectsCholesterol: true, affectsWeightGain: true),

// --- Diabetes / Sugar-related ingredients ---
  IngredientInfo(name: "Glucose", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Fructose", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Dextrose", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Maltodextrin", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "High fructose corn syrup", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Sugar syrup", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Condensed milk", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Sucrose", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Invert sugar", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Brown sugar", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Molasses", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Rice syrup", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Barley malt", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Dextrose monohydrate", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Fructose syrup", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Glucose syrup solids", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Honey powder", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Corn syrup", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Artificial sweetener (Aspartame)", affectsDiabetes: true),
  IngredientInfo(name: "Stevia extract", affectsDiabetes: true),

// --- Fatty liver / Processed or refined ingredients ---
  IngredientInfo(name: "Vanaspati", affectsFattyLiver: true, affectsWeightGain: true),
  IngredientInfo(name: "Refined palm oil", affectsFattyLiver: true, affectsWeightGain: true),
  IngredientInfo(name: "Refined sunflower oil", affectsFattyLiver: true, affectsWeightGain: true),
  IngredientInfo(name: "Refined soybean oil", affectsFattyLiver: true, affectsWeightGain: true),
  IngredientInfo(name: "Refined corn oil", affectsFattyLiver: true, affectsWeightGain: true),
  IngredientInfo(name: "Margarine powder", affectsFattyLiver: true, affectsWeightGain: true),
  IngredientInfo(name: "Shortening", affectsFattyLiver: true, affectsWeightGain: true),
  IngredientInfo(name: "Palm stearin", affectsFattyLiver: true, affectsWeightGain: true),
  IngredientInfo(name: "Refined soybean oil", affectsFattyLiver: true, affectsWeightGain: true),
  IngredientInfo(name: "Refined sunflower oil", affectsFattyLiver: true, affectsWeightGain: true),
  IngredientInfo(name: "Refined corn oil", affectsFattyLiver: true, affectsWeightGain: true),
  IngredientInfo(name: "Vegetable shortening", affectsFattyLiver: true, affectsWeightGain: true),
  IngredientInfo(name: "Hydrogenated vegetable fat", affectsFattyLiver: true, affectsWeightGain: true),
  IngredientInfo(name: "Vanaspati ghee", affectsFattyLiver: true, affectsWeightGain: true),
  IngredientInfo(name: "Bakery fat", affectsFattyLiver: true, affectsWeightGain: true),

// --- Common additives that may affect health ---
  IngredientInfo(name: "Vanillin", affectsDiabetes: true),
  IngredientInfo(name: "Artificial flavor", affectsCholesterol: true),
  IngredientInfo(name: "MSG (Monosodium Glutamate)", affectsCholesterol: true),
  IngredientInfo(name: "Emulsifiers", affectsCholesterol: true),
  IngredientInfo(name: "Soy lecithin", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Hydrogenated starch hydrolysates", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Corn flour", affectsDiabetes: true),
  IngredientInfo(name: "Malt extract", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Skimmed milk powder", affectsCholesterol: true),
  IngredientInfo(name: "Whole milk powder", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Casein", affectsCholesterol: true),
  IngredientInfo(name: "Lactose", affectsDiabetes: true),
  IngredientInfo(name: "Artificial sweetener (Aspartame)", affectsDiabetes: true),
  IngredientInfo(name: "Sodium caseinate", affectsCholesterol: true),
  IngredientInfo(name: "Hydrolyzed vegetable protein", affectsCholesterol: true),
  IngredientInfo(name: "Soy protein isolate", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Modified starch", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Polydextrose", affectsDiabetes: true),
  IngredientInfo(name: "High-Maltose Corn Syrup", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "Glucose-fructose syrup", affectsDiabetes: true, affectsWeightGain: true),
  IngredientInfo(name: "MSG (Monosodium Glutamate)", affectsCholesterol: true),
  IngredientInfo(name: "Emulsifiers", affectsCholesterol: true),
  IngredientInfo(name: "Vanillin", affectsDiabetes: true),
  IngredientInfo(name: "Artificial flavor", affectsCholesterol: true),

  // --- Dairy powders / Proteins ---
  IngredientInfo(name: "Skimmed milk powder", affectsCholesterol: true),
  IngredientInfo(name: "Whole milk powder", affectsCholesterol: true, affectsWeightGain: true),
  IngredientInfo(name: "Casein", affectsCholesterol: true),
  IngredientInfo(name: "Lactose", affectsDiabetes: true),
  IngredientInfo(name: "Sodium caseinate", affectsCholesterol: true),
  IngredientInfo(name: "Soy protein isolate", affectsCholesterol: true, affectsWeightGain: true),



  IngredientInfo(name: "oil", affectsCholesterol: true, affectsWeightGain: true),

  // --- FSSAI Banned Ingredients ---
  IngredientInfo(name: "Frysol", banned: true),
  IngredientInfo(name: "Fulvic acid (CHD-FA)", banned: true),
  IngredientInfo(name: "S-Adenosyl-L-Methionine disulfate P-toluene Sulfonate Tablets", banned: true),
  IngredientInfo(name: "S-Adenosyl-I-Methionine (SAMe)", banned: true),
  IngredientInfo(name: "Magnesium Threonate", banned: true),
  IngredientInfo(name: "Dipotassium orthophosphate (INS No-340(ii))", banned: true),
  IngredientInfo(name: "Silicon dioxide (INS No 551)", banned: true),
  IngredientInfo(name: "Starch (INS No 1405)", banned: true),
  IngredientInfo(name: "S-Adenosyl-L-Methionine P-toulensulfonate (Adonat®)", banned: true),
  IngredientInfo(name: "Herbal infusion (Rooibos with/without ingredients)", banned: true),
  IngredientInfo(name: "Acai Berry Fruit Juice Concentrate", banned: true),
  IngredientInfo(name: "Reboost Tablets", banned: true),
  IngredientInfo(name: "Sugar Jaggery", banned: true),
  IngredientInfo(name: "Super Life Total care 30 (STC30)", banned: true),
  IngredientInfo(name: "HemoHIM", banned: true),
  IngredientInfo(name: "Vitamin E Soft Gelatin Capsules", banned: true),
  IngredientInfo(name: "Notoginseng extract powder", banned: true),
  IngredientInfo(name: "Hydrogenated Vegetable Fat (Lauric Based)", banned: true),
  IngredientInfo(name: "Hydrogenated Vegetable Fat (Palm Based)", banned: true),
  IngredientInfo(name: "Refined Fractionated Hydrogenated Palm Kernel Oil", banned: true),
  IngredientInfo(name: "Refined Fractionated Palm Oil", banned: true),
  IngredientInfo(name: "Alkaline Water", banned: true),
  IngredientInfo(name: "Blackmores Nails, Hair and Skin", banned: true),
  IngredientInfo(name: "Blackmores Multivitamins for men", banned: true),
  IngredientInfo(name: "Lyophilized Bacterial Lysates for UTI Soft Capsules", banned: true),
  IngredientInfo(name: "Fungal Diastase, Papain, Activated Charcoal, Liquorice Tablets (Unienzyme XT)", banned: true),
  IngredientInfo(name: "Pectin based hair vitamin gummy candy with Biotin", banned: true),
  IngredientInfo(name: "Q-Force", banned: true),
  IngredientInfo(name: "Calcium D-Betahydroxybutyrate (Ca-BHB)", banned: true),
  IngredientInfo(name: "Trypsin Chymotrypsin", banned: true),
  IngredientInfo(name: "NHT Global Stemrenu", banned: true),
  IngredientInfo(name: "S-Adenosyl-L-Methionine disulfate p-toluenesulfonate (Adonat®)", banned: true),
  IngredientInfo(name: "S-Adenosyl-L-Methionine disulfate p-toluensesulfonate (Adonat®)", banned: true),
  IngredientInfo(name: "Low Sodium Sea Mineral Complex", banned: true),
  IngredientInfo(name: "Herbanova Supergreen", banned: true),
  IngredientInfo(name: "Ashwagandha Liquid concentrate (Aquasule)", banned: true),
  IngredientInfo(name: "Succinic Acid", banned: true),
  IngredientInfo(name: "Elemental Selenium (200mg/day from L-Selenomethionine)", banned: true),
  IngredientInfo(name: "KYRON T-314 Polacrilin Potassium", banned: true),
  IngredientInfo(name: "Raspberry ketone", banned: true),
  IngredientInfo(name: "Slica", banned: true),
  IngredientInfo(name: "Angelica sinensis", banned: true),
  IngredientInfo(name: "Paullinia cupana", banned: true),
  IngredientInfo(name: "Saw palmetto", banned: true),
  IngredientInfo(name: "Notoginseng", banned: true),
  IngredientInfo(name: "Chlorella growth factor", banned: true),
  IngredientInfo(name: "Pine bark extracted to Pinus radiata", banned: true),
  IngredientInfo(name: "Pine bark extracted from Pinus pinaster", banned: true),
  IngredientInfo(name: "Vitamin D3-veg", banned: true),
  IngredientInfo(name: "Chaga extract", banned: true),
  IngredientInfo(name: "Oxalobacter formigenes", banned: true),
  IngredientInfo(name: "Phytavail iron", banned: true),
  IngredientInfo(name: "Tea tree oil", banned: true),
  IngredientInfo(name: "Succinic acid", banned: true),
  IngredientInfo(name: "Inosine", banned: true),
  IngredientInfo(name: "Para amino benzoic acid (PABA)", banned: true),
  IngredientInfo(name: "Vanadium", banned: true),
  IngredientInfo(name: "Prenolit", banned: true),
  IngredientInfo(name: "Selenium dioxide", banned: true),
  IngredientInfo(name: "D-ribose", banned: true),
  IngredientInfo(name: "Ipriflavone", banned: true),
  IngredientInfo(name: "Polypodium leucotomos", banned: true),
];
