// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUMxmEfqiKYk3T66zf3UeVF-EWZSRrYRo',
    appId: '1:753848668770:web:e54b0b1136fcd1176a773b',
    messagingSenderId: '753848668770',
    projectId: 'safeeats-bd604',
    authDomain: 'safeeats-bd604.firebaseapp.com',
    storageBucket: 'safeeats-bd604.firebasestorage.app',
    measurementId: 'G-LPMK0C9C20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8XfVbFxywWMhP5bzdbv0BnrI3usc52W4',
    appId: '1:753848668770:android:afcee78b5b1a12016a773b',
    messagingSenderId: '753848668770',
    projectId: 'safeeats-bd604',
    storageBucket: 'safeeats-bd604.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ch-doY9jGt699eCN6NvdzNAw7L6-B7s',
    appId: '1:753848668770:ios:7642a22a5c4fc0c26a773b',
    messagingSenderId: '753848668770',
    projectId: 'safeeats-bd604',
    storageBucket: 'safeeats-bd604.firebasestorage.app',
    iosBundleId: 'com.example.safeeats1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ch-doY9jGt699eCN6NvdzNAw7L6-B7s',
    appId: '1:753848668770:ios:7642a22a5c4fc0c26a773b',
    messagingSenderId: '753848668770',
    projectId: 'safeeats-bd604',
    storageBucket: 'safeeats-bd604.firebasestorage.app',
    iosBundleId: 'com.example.safeeats1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUMxmEfqiKYk3T66zf3UeVF-EWZSRrYRo',
    appId: '1:753848668770:web:dcf0e852f758b9186a773b',
    messagingSenderId: '753848668770',
    projectId: 'safeeats-bd604',
    authDomain: 'safeeats-bd604.firebaseapp.com',
    storageBucket: 'safeeats-bd604.firebasestorage.app',
    measurementId: 'G-ZEJY16N1W1',
  );
}
